TheBookstown/Areas/Admin/Controllers/PagesTextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using TheBookstown.Areas.Admin.Models;
using TheBookstown.Domain;
using TheBookstown.Domain.Entities;
using TheBookstown.Service;
using TheBookstown.Models;

namespace TheBookstown.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PagesTextFieldsController : Controller
    {
        private readonly DataManager _dataManager;

        public PagesTextFieldsController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        [HttpGet]
        public IActionResult Edit(string codeWord)
        {
            var entity = _dataManager.PagesTextFields.GetPageTextFieldByCodeWord(codeWord);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(PageTextField entity)
        {
            if (ModelState.IsValid)
            {
                _dataManager.PagesTextFields.SavePageTextField(entity);
                return RedirectToAction(nameof(PagesTextFieldsController.Index), nameof(PagesTextFieldsController).CutController());
            }

            return View(entity);
        }

        public IActionResult Index(Guid id, string pageTitle, string codeWord, int page = 1, PTFSortState sortOrder = PTFSortState.CodeWordAsc)
        {
            int pageSize = 3;
            IQueryable<PageTextField> pageTextFields = _dataManager.PagesTextFields.GetPageTextFields();
            
            if (!string.IsNullOrWhiteSpace(codeWord))
            {
                pageTextFields = pageTextFields.Where(p => p.CodeWord!.Contains(codeWord));
            }

            if (!string.IsNullOrWhiteSpace(pageTitle))
            {
                pageTextFields = pageTextFields.Where(p => p.Name!.Contains(pageTitle));
            }

            pageTextFields = sortOrder switch
            {
                PTFSortState.CodeWordDesc => pageTextFields.OrderByDescending(p => p.CodeWord),
                PTFSortState.TitleAsc => pageTextFields.OrderBy(p => p.Name),
                PTFSortState.TitleDesc => pageTextFields.OrderByDescending(p => p.Name),
                _ => pageTextFields.OrderBy(p => p.CodeWord)
            };

            var count = pageTextFields.Count();
            var items = pageTextFields.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            var viewModel = new PTFIndexViewModel(items,
                new PageViewModel(count, page, pageSize),
                new PTFSortViewModel(sortOrder),
                new PTFFilterViewModel(pageTitle, codeWord));

            return View(viewModel);
        }
    }
}

TheBookstown/Areas/Admin/Views/PagesTextFields/Edit.cshtml
@model PageTextField
@{
    string strTitle = "Add or edit page data";
    ViewBag.Title = strTitle;
}

<div>
    <h1>@strTitle</h1>
    <div>
        <form asp-area="Admin" asp-controller="PagesTextFields" asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CodeWord" />
            <input type="hidden" asp-for="DateAdded" />
            <div asp-validation-summary="All"></div>
            <div>
                <label asp-for="Name"></label><br />
                <input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
            <div>
                <input type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

TheBookstown/Areas/Admin/Views/PagesTextFields/Index.cshtml
@model PTFIndexViewModel
@{
    string strTitle = "Pages data";
    ViewBag.Title = strTitle;
}

<div>
    <h1>@strTitle</h1>
    <div>
        <h2>Search by title or code word</h2>
        <div>
            <form method="get">
                <label>Title: </label>
                <input id="pageTitle" name="pageTitle" value="@(Model.FilterViewModel.SelectedTitle)" />
                <label>Code word: </label>
                <input id="codeWord" name="codeWord" value="@(Model.FilterViewModel.SelectedCodeWord)" />
                <input type="submit" value="Find" />
            </form>
        </div>
        <div>
            <table class="table table-borderless">
                <tr>
                    <th>
                        <a asp-area="Admin" 
                           asp-controller="PagesTextFields" 
                           asp-action="Index" 
                           asp-route-pageTitle="@(Model.FilterViewModel.SelectedTitle)"
                           asp-route-codeWord="@(Model.FilterViewModel.SelectedCodeWord)"
                           asp-route-sortOrder="@(Model.SortViewModel.CodeWordSort)">
                           Code word
                       </a>
                    </th>
                    <th>
                        <a asp-area="Admin"
                           asp-controller="PagesTextFields"
                           asp-action="Index"
                           asp-route-pageTitle="@(Model.FilterViewModel.SelectedTitle)"
                           asp-route-codeWord="@(Model.FilterViewModel.SelectedCodeWord)"
                           asp-route-sortOrder="@(Model.SortViewModel.TitleSort)">
                           Title
                       </a>
                    </th>
                </tr>
                @foreach (var item in Model.PagesTextFields)
                {
                    <tr>
                        <td>@item.CodeWord</td>
                        <td>@item.Name</td>
                        <td><a asp-area="Admin" asp-controller="PagesTextFields" asp-action="Edit" asp-route-codeWord="@item.CodeWord">Edit</a></td>
                    </tr>
                }
            </table>
            <page-link page-model="Model.PageViewModel" 
                       page-action="Index"
                       page-url-pageTitle="@(Model.FilterViewModel.SelectedTitle)"
                       page-url-codeWord="@(Model.FilterViewModel.SelectedCodeWord)"
                       page-url-sortOrder="@(Model.SortViewModel.Current)"></page-link>
        </div>
    </div>
</div>