TheBookstown/Models/SessionCartViewModel.cs
namespace TheBookstown.Models
{
    public class SessionCartViewModel
    {
        public BookViewModel? Book { get; set; }
        public int Quantity { get; set; }
    }
}

TheBookstown/Controllers/SessionCartController.cs
using Microsoft.AspNetCore.Mvc;
using TheBookstown.Areas.Admin.Controllers;
using TheBookstown.Areas.User.Controllers;
using TheBookstown.Domain;
using TheBookstown.Models;
using TheBookstown.Service;

namespace TheBookstown.Controllers
{
    public class SessionCartController : Controller
    {
        private readonly DataManager _dataManager;

        public SessionCartController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public IActionResult AddToCart(Guid id)
        {
            if (User.Identity!.IsAuthenticated) return BadRequest();

            var books = _dataManager.Books.GetBooksModels();

            if (SessionHelper.GetObjectFromJson<List<SessionCartViewModel>>(HttpContext.Session, "sessionCart") == null)
            {
                List<SessionCartViewModel> cart = new List<SessionCartViewModel>()
                {
                    new SessionCartViewModel { Book = books.FirstOrDefault(b => b.BookId == id), Quantity = 1 }
                };

                SessionHelper.SetObjectAsJson(HttpContext.Session, "sessionCart", cart);
            }
            else
            {
                List<SessionCartViewModel> cart = SessionHelper.GetObjectFromJson<List<SessionCartViewModel>>(HttpContext.Session, "sessionCart");
                int index = IsExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new SessionCartViewModel { Book = books.FirstOrDefault(b => b.BookId == id), Quantity = 1 });
                }

                SessionHelper.SetObjectAsJson(HttpContext.Session, "sessionCart", cart);
            }

            return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
        }

        public IActionResult Index()
        {
            if (User.Identity!.IsAuthenticated && User.IsInRole("ordinary"))
            {
                return RedirectToAction(nameof(UserCartController.Index), nameof(UserCartController).CutController(), new { area = "User" });
            }

            if (User.Identity!.IsAuthenticated && User.IsInRole("admin")) return BadRequest();

            var cart = SessionHelper.GetObjectFromJson<List<SessionCartViewModel>>(HttpContext.Session, "sessionCart");
            return View(cart);
        }

        public IActionResult Remove(Guid id)
        {
            if (User.Identity!.IsAuthenticated) return BadRequest();

            List<SessionCartViewModel> cart = SessionHelper.GetObjectFromJson<List<SessionCartViewModel>>(HttpContext.Session, "sessionCart");
            int index = IsExist(id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "sessionCart", cart);

            return RedirectToAction(nameof(SessionCartController.Index), nameof(SessionCartController).CutController());
        }

        private int IsExist(Guid id)
        {
            List<SessionCartViewModel> cart = SessionHelper.GetObjectFromJson<List<SessionCartViewModel>>(HttpContext.Session, "sessionCart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Book!.BookId.Equals(id))
                {
                    return i;
                }
            }

            return -1;
        }
    }
}

TheBookstown/Views/SessionCart/Index.cshtml
@model List<SessionCartViewModel>
@{
    string strTitle = "Cart";
    ViewBag.Title = strTitle;
}

<div>
    <h1>@strTitle</h1>
    <div>
        @if (Model is not null)
        {
            @if (Model.Count > 0)
            {
                <div>
                    <table>
                        <tr>
                            <th>Name</th><th>Price</th><th>Quantity</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Book!.BookName</td>
                                <td>@item.Book!.BookPrice</td>
                                <td>@item.Quantity</td>
                                <td>
                                    <form asp-area="" asp-controller="SessionCart" asp-action="Remove" asp-route-id="@item.Book.BookId" method="post">
                                        <input type="submit" value="Remove">
                                    </form>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            }
        }
        else
        {
            <h2>Cart is empty</h2>
        }
    </div>
</div>