TheBookstown/Areas/Admin/Controllers/GenresController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion.Internal;
using TheBookstown.Areas.Admin.Models;
using TheBookstown.Domain;
using TheBookstown.Domain.Entities;
using TheBookstown.Models;
using TheBookstown.Service;

namespace TheBookstown.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class GenresController : Controller
    {
        private readonly DataManager _dataManager;
        
        public GenresController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public IActionResult Edit(Guid id)
        {
            var entity = id == default ? new Genre() : _dataManager.Genres.GetGenreById(id);
            return View(entity);
        }

        [HttpPost]
        public IActionResult Edit(Genre entity)
        {
            if (ModelState.IsValid)
            {
                _dataManager.Genres.Save(entity);
                return RedirectToAction(nameof(GenresController.Index), nameof(GenresController).CutController());
            }

            return View(entity);
        }

        [HttpPost]
        public IActionResult Delete(Guid id)
        {
            _dataManager.Genres.Delete(id);
            return RedirectToAction(nameof(GenresController.Index), nameof(GenresController).CutController());
        }

        public IActionResult Index(Guid id, string genreName, int page = 1, GenresSortState sortOrder = GenresSortState.GenreNameAsc)
        {
            int pageSize = 3;
            IQueryable<Genre> genres = _dataManager.Genres.GetGenres();

            if (!string.IsNullOrWhiteSpace(genreName))
            {
                genres = genres.Where(g => g.Name!.Contains(genreName));
            }

            genres = sortOrder switch
            {
                GenresSortState.GenreNameDesc => genres.OrderByDescending(g => g.Name),
                _ => genres.OrderBy(g => g.Name)
            };

            var count = genres.Count();
            var items = genres.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            var viewModel = new GenresIndexViewModel(items, 
                new PageViewModel(count, page, pageSize),
                new GenresSortViewModel(sortOrder),
                new GenresFilterViewModel(genreName));

            return View(viewModel);
        }
    }
}

TheBookstown/Areas/Admin/Views/Genres/Edit.cshtml
@model Genre
@{
    string strTitle = "Add or edit genre";
    ViewBag.Title = strTitle;
}

<div>
    <h1>@strTitle</h1>
    <div>
        <form asp-area="Admin" asp-controller="Genres" asp-action="Edit" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="DateAdded" />
            <div asp-validation-summary="All"></div>
            <div>
                <label asp-for="Name"></label><br />
                <input asp-for="Name" />
                <span asp-validation-for="Name"></span>
            </div>
            <div>
                <input type="submit" value="Save" />
            </div>
        </form>
    </div>
</div>

TheBookstown/Areas/Admin/Views/Genres/Index.cshtml
@model GenresIndexViewModel
@{
    string strTitle = "Genres";
    ViewBag.Title = strTitle;
}

<div>
    <h1>@strTitle</h1>
    <div>
        <h2>Search by genre name</h2>
        <div>
            <form method="get">
                <label>Name: </label>
                <input id="genreName" name="genreName" value="@Model.FilterViewModel.SelectedName" />
                <input type="submit" value="Find" />
            </form>
        </div>
        <div>
            <a asp-area="Admin" asp-controller="Genres" asp-action="Edit" asp-route-id="">Add a new genre</a>
        </div>
        <div>
            <table class="table table-borderless">
                <tr>
                    <th>
                        <a asp-area="Admin"
                           asp-controller="Genres"
                           asp-action="Index"
                           asp-route-sortOrder="@(Model.SortViewModel.NameSort)"
                           asp-route-genreName="@(Model.FilterViewModel.SelectedName)">
                           Name
                       </a>
                    </th>
                </tr>
                @foreach (var item in Model.Genres)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td><a asp-area="Admin" asp-controller="Genres" asp-action="Edit" asp-route-id="@item.Id">Edit</a></td>
                        <td>
                            <form asp-area="Admin" asp-controller="Genres" asp-action="Delete" asp-route-id="@item.Id" method="post">
                                <input type="submit" value="Delete">
                            </form>
                        </td>
                    </tr>
                }
            </table>
            <page-link page-model="Model.PageViewModel" page-action="Index"
                       page-url-genreName="@(Model.FilterViewModel.SelectedName)"
                       page-url-sortOrder="@(Model.SortViewModel.Current)"></page-link>
        </div>
    </div>
</div>